
’	root"_tf_keras_model*ò{"name": "pos_tagger", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "PosTagger", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [10]}, "string", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [10]}, "string", "input_1"]}, "keras_version": "2.8.0", "backend": "tensorflow", "model_config": {"class_name": "PosTagger"}, "training_config": {"loss": {"class_name": "MaskedLoss", "config": {"reduction": null, "name": "masked_loss"}, "shared_object_id": 0}, "metrics": null, "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
æroot.tagvec"_tf_keras_layer*½{"name": "tag_vectorization", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TagVectorization", "config": {"name": "tag_vectorization", "trainable": true, "dtype": "float32"}, "shared_object_id": 1}2
­	root.bert"_tf_keras_layer*†{"name": "bert_embeddings", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "BertEmbeddings", "config": {"layer was saved without config": true}}2
úroot.tagger"_tf_keras_layer*Ñ{"name": "tagger__attention", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Tagger_Attention", "config": {"a": 44}, "shared_object_id": 2, "build_input_shape": {"class_name": "TensorShape", "items": [null, 110, 128]}}2
ºroot.acc"_tf_keras_metric*“{"class_name": "MaskedAccuracy", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32"}, "shared_object_id": 3}2
«root.bert.bert"_tf_keras_layer*ÿ{"name": "keras_layer", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"name": "keras_layer", "trainable": true, "dtype": "float32", "handle": "https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1"}, "shared_object_id": 4}2
°root.bert.tokenize"_tf_keras_layer*€{"name": "keras_layer_1", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"layer was saved without config": true}}2
±root.bert.bert_pack"_tf_keras_layer*€{"name": "keras_layer_2", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"layer was saved without config": true}}2
–root.tagger.attention"_tf_keras_layer*ã{"name": "attention", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Attention", "config": {"name": "attention", "trainable": true, "dtype": "float32", "causal": false, "dropout": 0.0, "use_scale": false}, "shared_object_id": 5, "build_input_shape": [{"class_name": "TensorShape", "items": [null, 110, 44]}, {"class_name": "TensorShape", "items": [null, 110, 44]}]}2