
’	root"_tf_keras_model*ò{"name": "pos_tagger_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "PosTagger", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [1]}, "string", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [1]}, "string", "input_1"]}, "keras_version": "2.8.0", "backend": "tensorflow", "model_config": {"class_name": "PosTagger"}, "training_config": {"loss": {"class_name": "MaskedLoss", "config": {"reduction": null, "name": "masked_loss"}, "shared_object_id": 0}, "metrics": null, "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
êroot.tagvec"_tf_keras_layer*Á{"name": "tag_vectorization_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TagVectorization", "config": {"name": "tag_vectorization_1", "trainable": true, "dtype": "float32"}, "shared_object_id": 1}2
¯	root.bert"_tf_keras_layer*ˆ{"name": "bert_embeddings_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "BertEmbeddings", "config": {"layer was saved without config": true}}2
£root.tagger"_tf_keras_layer*ú{"name": "tagger__dense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Tagger_Dense", "config": {"a": 44}, "shared_object_id": 2}2
ºroot.acc"_tf_keras_metric*“{"class_name": "MaskedAccuracy", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32"}, "shared_object_id": 3}2
¯root.bert.bert"_tf_keras_layer*ƒ{"name": "keras_layer_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"name": "keras_layer_3", "trainable": true, "dtype": "float32", "handle": "https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1"}, "shared_object_id": 4}2
°root.bert.tokenize"_tf_keras_layer*€{"name": "keras_layer_4", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"layer was saved without config": true}}2
±root.bert.bert_pack"_tf_keras_layer*€{"name": "keras_layer_5", "trainable": false, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KerasLayer", "config": {"layer was saved without config": true}}2
Ároot.tagger.dense"_tf_keras_layer*’{"name": "dense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 44, "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 5}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 6}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "shared_object_id": 7, "input_spec": {"class_name": "InputSpec", "config": {"dtype": null, "shape": null, "ndim": null, "max_ndim": null, "min_ndim": 2, "axes": {"-1": 128}}, "shared_object_id": 8}, "build_input_shape": {"class_name": "TensorShape", "items": [null, 110, 128]}}2